name: recipe
description: Recipe Finder.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.2
  flutter_slidable: ^2.0.0
  flutter_svg: ^1.1.4
  shared_preferences: ^2.0.15
  json_annotation: ^4.6.0
  http: ^0.13.5
  chopper: ^4.0.6
  logging: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  chopper_generator: ^4.0.6

flutter:

  uses-material-design: true

  assets:
    - assets/recipes1.json
    - assets/recipes2.json
    - assets/images/
